language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get -y install libffi-dev libgmp-dev libtool libsecp256k1-dev
  - cd src
install:
  - pip install -e .
  - pip install fastapi[all]
script:
  - python setup.py test
after_success:
  - codecov
