language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get -y install libffi-dev libgmp-dev libtool
  - cd src
install:
  - pip install -e .
script:
  - python setup.py test
after_success:
  - codecov
