site_name: petition-tp-python
site_url: https://decodeproject.github.io/petition-tp-python
repo_url: https://github.com/DECODEproject/petition-tp-python
site_author: Puria Nafisi Azizi
site_description: Petition Transaction Processor for Hyperledger Sawtooth
copyright: Copyright (C) 2019 by the <a href="https://dyne.org">Dyne.org foundation</a>. The source code is licensed <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3</a>.

extra:
  links:
    docker: https://hub.docker.com/r/dyne/sawroom
  drift_handle: s64nd7w43g53
  nav:
    subtitle: This is an awesome project
    logo: null # /img/redroom-trans.png
    og_image_large: null # /img/redroom-trans.png


plugins: []

extra_css:
  - //fonts.googleapis.com/css?family=Montserrat&display=swap
  - css/custom.css

markdown_extensions:
  - admonition
  - codehilite

theme:
  name: null
  custom_dir: 'mkdocs-dyne-theme/'
